"use client";
import {useState,useEffect,useRef,type ReactNode,type FormEvent} from 'react';
import {Upload} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {fixtures} from '@/lib/league';
import {Choose,Badge,type Data,type Modal} from './league';
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field">{label}{children}</label>}
export default function Editor({modal:m,data,seasonId,busy,close,save}:{modal:Modal;data:Data;seasonId:string;busy:boolean;close:()=>void;save:(b:Record<string,unknown>,version?:number)=>Promise<unknown>}){
 const [version]=useState(data.version),[name,setName]=useState(m.profile?.name||m.competition?.name||m.season?.name||''),[team,setTeam]=useState(m.profile?.team||''),[badge,setBadge]=useState(m.profile?.badge||''),[active,setActive]=useState(m.profile?.active??true),[date,setDate]=useState(m.competition?.date||new Date().toLocaleDateString('en-CA')),[sid,setSid]=useState(m.competition?.seasonId||seasonId),[players,setPlayers]=useState(m.competition?.players||[]),[legs,setLegs]=useState<1|2>(m.competition?.legs||1),[hs,setHs]=useState(m.match?.hs?.toString()??''),[as,setAs]=useState(m.match?.as?.toString()??''),[current,setCurrent]=useState(m.season?.id===data.state.currentSeason),[err,setErr]=useState(''),[uploading,setUploading]=useState(false),[image,setImage]=useState<HTMLImageElement|null>(null),[imageUrl,setImageUrl]=useState(''),[zoom,setZoom]=useState(1),[x,setX]=useState(50),[y,setY]=useState(50),[preview,setPreview]=useState(false);
 const canvas=useRef<HTMLCanvasElement>(null);const locked=!!m.competition&&data.state.matches.some(x=>x.competitionId===m.competition!.id&&x.revision>0);const schedules=preview?fixtures(players,legs,'preview'):[];
 useEffect(()=>()=>{if(imageUrl)URL.revokeObjectURL(imageUrl)},[imageUrl]);
 useEffect(()=>{if(!image||!canvas.current)return;const ctx=canvas.current.getContext('2d')!;const side=Math.min(image.naturalWidth,image.naturalHeight)/zoom;ctx.clearRect(0,0,512,512);ctx.drawImage(image,(image.naturalWidth-side)*x/100,(image.naturalHeight-side)*y/100,side,side,0,0,512,512)},[image,zoom,x,y]);
 function chooseFile(file?:File){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024){setErr('เลือก PNG, JPG หรือ WebP ไม่เกิน 10 MB');return}const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{setImageUrl(url);setImage(img);setZoom(1);setX(50);setY(50);setErr('')};img.onerror=()=>{URL.revokeObjectURL(url);setErr('เปิดรูปนี้ไม่ได้')};img.src=url}
 async function upload(){if(!canvas.current)return;setUploading(true);try{const blob=await new Promise<Blob|null>(r=>canvas.current!.toBlob(r,'image/png'));if(!blob)throw new Error('แปลงรูปไม่สำเร็จ');const r=await fetch('/api/badge',{method:'POST',headers:{'Content-Type':'image/png'},body:blob});const d=await r.json() as {error:string;key:string};if(!r.ok)throw new Error(d.error);setBadge(d.key);setImage(null)}catch(e){setErr((e as Error).message)}finally{setUploading(false)}}
 async function submit(e:FormEvent){e.preventDefault();setErr('');try{if(m.kind==='profile'){if(image)throw new Error('กดใช้รูปนี้ก่อนบันทึก');await save({action:'profile',profile:{id:m.profile?.id,name,team,badge,active}},version)}else if(m.kind==='competition'){await save({action:'competition',competition:{id:m.competition?.id,name,date,seasonId:sid,players,legs}},version)}else if(m.kind==='season'){await save({action:'season',id:m.season?.id,name,current},version)}else if(m.kind==='score'){if(hs===''||as==='')throw new Error('กรอกสกอร์ทั้งสองทีม');await save({action:'score',id:m.match!.id,hs:Number(hs),as:Number(as)},version)}}catch(e){setErr((e as Error).message)}}
 const titles={profile:m.profile?'แก้ไขโปรไฟล์':'เพิ่มโปรไฟล์',competition:m.competition?'แก้ไขโปรแกรม':'สร้างโปรแกรมการแข่งขัน',score:'บันทึกผลการแข่งขัน',season:m.season?'แก้ไขฤดูกาล':'สร้างฤดูกาล'};
 return <Dialog open onOpenChange={v=>!v&&!busy&&!uploading&&close()}><DialogContent className="modal"><DialogTitle>{titles[m.kind as keyof typeof titles]}</DialogTitle><DialogDescription>{m.kind==='score'?'ผลมีผลทันที · Undo ได้ 30 วินาที และคืนค่าจากประวัติได้':m.kind==='competition'?'เลือกผู้เล่นที่มีโปรไฟล์แล้ว เพื่อจัดคู่แข่งขันอัตโนมัติ':'FC Friends League'}</DialogDescription><form className="form-stack" onSubmit={submit}>
 {m.kind==='score'?<><div className="score-inputs"><Field label={`${data.state.profiles.find(p=>p.id===m.match!.home)?.name} (เหย้า)`}><input aria-label="ประตูเจ้าบ้าน" type="number" min={0} max={99} step={1} value={hs} onChange={e=>setHs(e.target.value)} required/></Field><span>:</span><Field label={`${data.state.profiles.find(p=>p.id===m.match!.away)?.name} (เยือน)`}><input aria-label="ประตูทีมเยือน" type="number" min={0} max={99} step={1} value={as} onChange={e=>setAs(e.target.value)} required/></Field></div>{m.match!.hs!==null&&<Button type="button" variant="outline" disabled={busy} onClick={async()=>{try{await save({action:'score',id:m.match!.id,hs:null,as:null},version)}catch(e){setErr((e as Error).message)}}}>ล้างผล · กลับเป็นยังไม่แข่ง</Button>}</>:<><Field label={m.kind==='profile'?'ชื่อผู้เล่น':m.kind==='season'?'ชื่อฤดูกาล':'ชื่อโปรแกรม'}><input value={name} onChange={e=>setName(e.target.value)} maxLength={60} required/></Field>
 {m.kind==='profile'&&<><Field label="ชื่อทีม Ultimate Team (ไม่บังคับ)"><input value={team} onChange={e=>setTeam(e.target.value)} maxLength={60}/></Field><div className="actions"><Badge p={{id:'',name,team,badge,active}}/><Button type="button" variant="ghost" onClick={()=>{setBadge('');setImage(null)}}>ลบตราสโมสร</Button></div><Field label="อัปโหลดตราสโมสร (PNG / JPG / WebP)"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>chooseFile(e.target.files?.[0])}/></Field>{image&&<div className="form-stack"><canvas ref={canvas} width={512} height={512} className="crop-canvas"/><Field label="ขยายรูป"><Slider aria-label="ขยายรูป" min={1} max={3} step={.05} value={[zoom]} onValueChange={v=>setZoom(v[0])}/></Field><Field label="ตำแหน่งแนวนอน"><Slider aria-label="ตำแหน่งแนวนอน" value={[x]} onValueChange={v=>setX(v[0])}/></Field><Field label="ตำแหน่งแนวตั้ง"><Slider aria-label="ตำแหน่งแนวตั้ง" value={[y]} onValueChange={v=>setY(v[0])}/></Field><Button type="button" disabled={uploading} onClick={upload}><Upload size={16}/>{uploading?'กำลังอัปโหลด…':'ใช้รูปนี้'}</Button></div>}<label className="check-row"><Switch checked={active} onCheckedChange={setActive}/> เปิดใช้งานโปรไฟล์</label></>}
 {m.kind==='season'&&<label className="check-row"><Switch checked={current} onCheckedChange={setCurrent}/> กำหนดเป็นฤดูกาลปัจจุบัน</label>}
 {m.kind==='competition'&&<><Field label="วันที่แข่งขัน"><input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></Field><div className="field">ฤดูกาล<Choose value={sid} onChange={v=>{if(!locked)setSid(v)}} items={data.state.seasons} label="ฤดูกาล"/></div>{locked&&<p className="muted">มีประวัติผลแล้ว แก้ไขได้เฉพาะชื่อและวันที่</p>}<div className="field">รูปแบบ<Choose value={String(legs)} onChange={v=>{if(!locked){setLegs(Number(v) as 1|2);setPreview(false)}}} items={[{id:'1',name:'พบกัน 1 นัด'},{id:'2',name:'พบกัน 2 นัด · เหย้า–เยือน'}]} label="รูปแบบการแข่งขัน"/></div><div className="form-stack"><strong>เลือกผู้เข้าร่วม ({players.length} คน)</strong>{data.state.profiles.filter(p=>p.active||players.includes(p.id)).map(p=><label className="check-row" key={p.id}><Checkbox checked={players.includes(p.id)} disabled={locked} onCheckedChange={v=>{setPlayers(v?[...players,p.id]:players.filter(x=>x!==p.id));setPreview(false)}}/><Badge p={p}/>{p.name}</label>)}</div><p className="muted">รวม {players.length*(players.length-1)/2*legs} แมตช์ · แต่ละคนแข่ง {Math.max(0,players.length-1)*legs} นัด</p><Button type="button" variant="outline" disabled={players.length<2} onClick={()=>setPreview(!preview)}>{preview?'ซ่อน':'ตรวจสอบ'} คู่แข่งขัน</Button>{preview&&<div className="fixture-preview">{schedules.map((f,i)=><p key={i}>รอบ {f.round} · {data.state.profiles.find(p=>p.id===f.home)?.name} — {data.state.profiles.find(p=>p.id===f.away)?.name}</p>)}</div>}</>}
 </>}
 {err&&<p className="error" role="alert">{err} {err.includes('ล่าสุด')&&<span>ปิดหน้าต่างแล้วเปิดใหม่เพื่อใช้ข้อมูลล่าสุด</span>}</p>}<div className="actions"><Button type="submit" disabled={busy||uploading||(m.kind==='competition'&&players.length<2)}>{busy?'กำลังบันทึก…':'บันทึก'}</Button><Button type="button" variant="outline" disabled={busy||uploading} onClick={close}>ยกเลิก</Button></div></form></DialogContent></Dialog>
}
