"use client";
import {useEffect,useState,useRef,useCallback,type ReactNode} from 'react';
import {Trophy,Plus,CalendarDays,LockKeyhole,Pencil,RotateCcw,LogOut} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Skeleton} from '@/components/ui/skeleton';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Toaster,toast} from 'sonner';
import {standings,type LeagueState,type Profile,type Competition,type Match,type Season} from '@/lib/league';
import Editor from './editor';
export type Data={state:LeagueState;version:number;authenticated:boolean;configured:boolean;setupAllowed:boolean};
export type Modal={kind:'login'|'profile'|'competition'|'score'|'season';profile?:Profile;competition?:Competition;match?:Match;season?:Season};
export function Choose({value,onChange,items,label}:{value:string;onChange:(x:string)=>void;items:{id:string;name:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.id} value={i.id}>{i.name}</SelectItem>)}</SelectContent></Select>}
export function Badge({p}:{p?:Profile}){return p?.badge?<img className="badge-img" src={`/api/badge?key=${encodeURIComponent(p.badge)}`} alt={`ตราสโมสร ${p.name}`}/>:<span className="avatar">{p?.name.slice(0,2)||'FF'}</span>}
function NoData({title,children}:{title:string;children:ReactNode}){return <Empty><EmptyHeader><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{children}</EmptyDescription></EmptyHeader></Empty>}
const scoreText=(x:[number|null,number|null])=>x[0]===null?'ยังไม่แข่ง':`${x[0]} – ${x[1]}`;
export default function League(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('table'),[season,setSeason]=useState(''),[competition,setCompetition]=useState('all'),[modal,setModal]=useState<Modal|null>(null),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState<{title:string;description:string;action:()=>Promise<void>}|null>(null);
 const latest=useRef<Data|null>(null);
 const refresh=useCallback(async()=>{const r=await fetch('/api/league',{cache:'no-store'});const d=await r.json() as Data & {error:string};if(!r.ok)throw new Error(d.error);setData(d);latest.current=d;setError('');setSeason(x=>x||d.state.currentSeason);return d as Data},[]);
 useEffect(()=>{refresh().catch(e=>setError(e.message));const t=setInterval(()=>refresh().catch(()=>{}),20000);return()=>clearInterval(t)},[refresh]);
 async function mutate(body:Record<string,unknown>,version?:number){setBusy(true);try{const r=await fetch('/api/league',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,version:version??latest.current?.version})});const d=await r.json() as {error:string;eventId?:string};if(!r.ok)throw new Error(d.error);await refresh();setModal(null);if(d.eventId){const event=latest.current!.state.history.find(h=>h.id===d.eventId)!;toast.success('บันทึกแล้ว · ตารางคะแนนอัปเดตทันที',{duration:30000,action:{label:'เลิกทำ',onClick:()=>{mutate({action:'restore',id:event.matchId,eventId:event.id,undo:true}).catch(e=>toast.error(e.message))}}})}else toast.success('บันทึกเรียบร้อย');return d}finally{setBusy(false)}}
 const guard=(m:Modal)=>{setModal(data?.authenticated?m:{kind:'login'})};
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const ctrl=new AbortController();Promise.resolve(context.registerTool({name:'read_league_standings',description:'Read FC Friends League standings for an existing season',inputSchema:{type:'object',properties:{seasonId:{type:'string'}},required:['seasonId'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const id=(input as {seasonId?:string})?.seasonId;const d=await refresh();if(typeof id!=='string'||!d.state.seasons.some(x=>x.id===id))throw new Error('Unknown season');return standings(d.state,id)}},{signal:ctrl.signal})).catch(()=>{});return()=>ctrl.abort()},[refresh]);
 const s=data?.state,p=(id:string)=>s?.profiles.find(p=>p.id===id),comps=s?.competitions.filter(c=>c.seasonId===season)||[],active=comps.filter(c=>!c.archived),matches=s?.matches.filter(m=>active.some(c=>c.id===m.competitionId))||[],rows=s?standings(s,season):[],completed=matches.filter(m=>m.hs!==null),next=matches.find(m=>m.hs===null),recent=[...completed].sort((a,b)=>(s?.history.find(h=>h.matchId===b.id)?.time||'').localeCompare(s?.history.find(h=>h.matchId===a.id)?.time||'')).slice(0,4);
 const run=(fn:()=>Promise<unknown>)=>{fn().catch(e=>toast.error(e.message))};
 function matchRow(m:Match){return <div className="list-row" key={m.id}><div className="match-team"><Badge p={p(m.home)}/><strong>{p(m.home)?.name}</strong><small>เหย้า</small></div><button className="score score-button" title="กรอกหรือแก้ไขผล" onClick={()=>guard({kind:'score',match:m})}>{m.hs===null?'VS':`${m.hs} : ${m.as}`}</button><div className="match-team"><Badge p={p(m.away)}/><strong>{p(m.away)?.name}</strong><small>เยือน</small></div><Button size="sm" variant="ghost" onClick={()=>guard({kind:'score',match:m})}><Pencil size={14}/>{m.hs===null?'กรอกผล':'แก้ไข'}</Button></div>}
 return <main className="shell"><Toaster theme="dark" richColors position="bottom-right"/><header><div className="brand"><span className="crest">FFL</span><div>FC FRIENDS LEAGUE<small>ULTIMATE TEAM · FC27</small></div></div><Button variant="outline" disabled={!data} onClick={()=>data?.authenticated?run(()=>mutate({action:'logout'})):setModal({kind:'login'})}>{data?.authenticated?<LogOut size={16}/>:<LockKeyhole size={16}/>}<span>{data?.authenticated?'ออกจากการจัดการ':'เข้าสู่การจัดการ'}</span></Button></header><section className="mast"><div><p className="eyebrow">THE LEAGUE. YOUR LEGACY.</p><h1>สนามของเพื่อน <em>เวทีของแชมป์.</em></h1><p className="muted">{s?.seasons.find(x=>x.id===season)?.name||'FC Friends League'} · {active.length} โปรแกรม · {completed.length} / {matches.length} แมตช์</p></div><div className="season-mark"><Trophy size={36}/><strong>FFL / 27</strong></div></section>
 {error&&<div className="error">{error} <Button variant="outline" onClick={()=>run(refresh)}>ลองใหม่</Button></div>}
 {!data?<div className="form-stack"><Skeleton className="h-12"/><Skeleton className="h-64"/></div>:<><div className="toolbar"><Choose value={season} onChange={v=>{setSeason(v);setCompetition('all')}} items={s!.seasons} label="เลือกฤดูกาล"/><span className="muted-text">{data.authenticated?'โหมดจัดการ · ทุกคนแก้ไขได้':'โหมดดูข้อมูล'}</span></div><Tabs value={tab} onValueChange={setTab}><div className="tabs-scroll"><TabsList variant="line" className="league-tabs">{[['table','ตารางคะแนน'],['matches','โปรแกรมการแข่งขัน'],['profiles','โปรไฟล์'],['seasons','ฤดูกาล'],['history','ประวัติผล']].map(([id,label])=><TabsTrigger key={id} value={id}>{label}</TabsTrigger>)}</TabsList></div>
 <TabsContent value="table"><div className="section-title"><div><p className="eyebrow">LEAGUE TABLE</p><h2>ตารางคะแนน</h2></div><Button onClick={()=>guard({kind:'competition'})}><Plus size={16}/> สร้างโปรแกรม</Button></div><div className="dashboard"><section className="panel">{rows.length?<Table><TableHeader><TableRow>{['อันดับ','ผู้เล่น / สโมสร','แข่ง','ชนะ','เสมอ','แพ้','ได้','เสีย','+/-','คะแนน'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={r.profile.id}><TableCell>{String(i+1).padStart(2,'0')}</TableCell><TableCell><div className="player"><Badge p={r.profile}/><div><strong>{r.profile.name}</strong><small>{r.profile.team||'ยังไม่ระบุชื่อทีม'}</small></div></div></TableCell>{[r.played,r.won,r.drawn,r.lost,r.gf,r.ga,r.gd].map((v,j)=><TableCell key={j}>{v}</TableCell>)}<TableCell className="points">{r.points}</TableCell></TableRow>)}</TableBody></Table>:<NoData title="ฤดูกาลใหม่ เริ่มที่แมตช์แรก">สร้างโปรแกรมแล้วเลือกผู้เข้าร่วม เพื่อเริ่มตารางคะแนน</NoData>}<p className="table-note">ชนะ 3 · เสมอ 1 · แพ้ 0 คะแนน<br/>คะแนน → ผลต่างประตู → ประตูได้ → คะแนนพบกันในกลุ่มที่เสมอกัน<br/>หากยังเท่ากัน เรียงชื่อเพื่อแสดงผล · จำนวนแมตช์แต่ละคนอาจไม่เท่ากัน</p></section><aside className="panel padded"><CalendarDays className="gold"/><p className="eyebrow">NEXT MATCHDAY</p><h2>{next?`${p(next.home)?.name} × ${p(next.away)?.name}`:'พร้อมเริ่มฤดูกาล?'}</h2><p className="muted">{next?active.find(c=>c.id===next.competitionId)?.name:'เลือกเพื่อนที่เข้าร่วม แล้วให้ระบบจัดคู่แข่งขันให้'}</p><Button variant="outline" onClick={()=>next?guard({kind:'score',match:next}):guard({kind:'competition'})}>{next?'บันทึกผล':'สร้างโปรแกรมแรก'}</Button><p className="muted">{s!.profiles.filter(p=>p.active).length} ผู้เล่นพร้อมลงสนาม</p></aside></div><div className="section-title"><h2>ผลล่าสุด</h2><Button variant="ghost" onClick={()=>setTab('matches')}>ดูโปรแกรมทั้งหมด</Button></div><div className="panel">{recent.length?recent.map(matchRow):<NoData title="ยังไม่มีผลการแข่งขัน">เมื่อบันทึกสกอร์ ผลล่าสุดจะแสดงที่นี่</NoData>}</div></TabsContent>
 <TabsContent value="matches"><div className="section-title"><div><p className="eyebrow">MATCHDAYS</p><h2>โปรแกรมการแข่งขัน</h2></div><Button onClick={()=>guard({kind:'competition'})}><Plus size={16}/> สร้างโปรแกรม</Button></div><Choose value={competition} onChange={setCompetition} items={[{id:'all',name:'ทุกโปรแกรม'},...comps]} label="เลือกโปรแกรม"/>{!comps.length&&<NoData title="ยังไม่มีโปรแกรมในฤดูกาลนี้">เลือกผู้เล่นอย่างน้อย 2 คน แล้วสร้างตารางแบบ 1 หรือ 2 นัด</NoData>}{comps.filter(c=>competition==='all'||competition===c.id).map(c=><section className="panel competition-panel" key={c.id}><div className="list-row"><div><h2>{c.name} {c.archived&&<small>เก็บเข้าคลัง · ไม่นับคะแนน</small>}</h2><small>{c.date} · {c.players.length} ผู้เล่น · พบกัน {c.legs} นัด</small></div><div className="actions"><Button variant="outline" onClick={()=>guard({kind:'competition',competition:c})}><Pencil size={14}/> แก้ไข</Button><Button variant="ghost" onClick={()=>{if(!data.authenticated){setModal({kind:'login'});return}setConfirm({title:c.archived?'กู้คืนโปรแกรม?':'เก็บโปรแกรมเข้าคลัง?',description:c.archived?'ผลทั้งหมดจะกลับมาคิดคะแนนอีกครั้ง':'ผลและประวัติยังอยู่ แต่คะแนนของโปรแกรมนี้จะถูกนำออกจากตาราง สามารถกู้คืนได้',action:async()=>{await mutate({action:'archive',id:c.id,archived:!c.archived},data.version)}})}}>{c.archived?'กู้คืน':'เก็บเข้าคลัง'}</Button></div></div>{!c.archived&&Array.from(new Set(s!.matches.filter(m=>m.competitionId===c.id).map(m=>m.round))).map(round=><div key={round}><p className="round-label">รอบ {round}</p>{s!.matches.filter(m=>m.competitionId===c.id&&m.round===round).map(matchRow)}</div>)}</section>)}</TabsContent>
 <TabsContent value="profiles"><div className="section-title"><div><p className="eyebrow">THE CLUBS</p><h2>โปรไฟล์ผู้เล่น</h2></div><Button onClick={()=>guard({kind:'profile'})}><Plus size={16}/> เพิ่มผู้เล่น</Button></div><div className="cards">{s!.profiles.map(p=><section className="panel padded profile-card" key={p.id}><Badge p={p}/><h2>{p.name}</h2><p className="muted">{p.team||'เพิ่มชื่อทีม Ultimate Team ได้ภายหลัง'}</p><small>{p.active?'พร้อมเข้าร่วมโปรแกรม':'ปิดใช้งาน · ประวัติยังคงอยู่'}</small><Button variant="outline" onClick={()=>guard({kind:'profile',profile:p})}><Pencil size={15}/> แก้ไขโปรไฟล์</Button></section>)}</div></TabsContent>
 <TabsContent value="seasons"><div className="section-title"><div><p className="eyebrow">SEASONS</p><h2>ฤดูกาล</h2></div><Button onClick={()=>guard({kind:'season'})}><Plus size={16}/> สร้างฤดูกาล</Button></div><div className="panel">{s!.seasons.map(x=><div className="list-row" key={x.id}><div><h2>{x.name}</h2><small>{s!.currentSeason===x.id?'ฤดูกาลปัจจุบัน':`${s!.competitions.filter(c=>c.seasonId===x.id).length} โปรแกรม`}</small></div><div className="actions"><Button variant="ghost" onClick={()=>{setSeason(x.id);setTab('table')}}>ดูตารางคะแนน</Button><Button variant="outline" onClick={()=>guard({kind:'season',season:x})}>แก้ไข</Button></div></div>)}</div></TabsContent>
 <TabsContent value="history"><div className="section-title"><div><p className="eyebrow">MATCH HISTORY</p><h2>ประวัติการแก้ไขผล</h2></div></div><p className="muted">คืนค่าผลก่อนหน้าของรายการที่เลือก โดยระบบจะบันทึกการคืนค่าเป็นประวัติใหม่</p><div className="panel">{s!.history.filter(h=>comps.some(c=>c.id===s!.matches.find(m=>m.id===h.matchId)?.competitionId)).map(h=>{const m=s!.matches.find(m=>m.id===h.matchId)!;return <div className="list-row" key={h.id}><div><strong>{p(m.home)?.name} × {p(m.away)?.name}</strong><small>{new Date(h.time).toLocaleString('th-TH')} · {h.kind}</small><p>{scoreText(h.before)} → <span className="gold">{scoreText(h.after)}</span></p></div><Button variant="outline" onClick={()=>{if(!data.authenticated){setModal({kind:'login'});return}setConfirm({title:'คืนค่าผลการแข่งขัน?',description:`ผลปัจจุบัน ${scoreText([m.hs,m.as])} จะเปลี่ยนเป็น ${scoreText(h.before)} และตารางคะแนนจะอัปเดตทันที`,action:async()=>{await mutate({action:'restore',id:m.id,eventId:h.id},data.version)}})}}><RotateCcw size={14}/> คืนค่าก่อนรายการนี้</Button></div>})}{!s!.history.some(h=>comps.some(c=>c.id===s!.matches.find(m=>m.id===h.matchId)?.competitionId))&&<NoData title="ยังไม่มีการแก้ไขผล">ทุกการบันทึก แก้ไข ล้างผล และคืนค่าจะถูกเก็บไว้ที่นี่</NoData>}</div></TabsContent></Tabs></>}
 {modal&&data&&<Editor key={`${modal.kind}-${modal.profile?.id||modal.competition?.id||modal.match?.id||modal.season?.id||'new'}`} modal={modal} data={data} seasonId={season} busy={busy} close={()=>setModal(null)} save={mutate}/>}
 <AlertDialog open={!!confirm} onOpenChange={open=>!open&&setConfirm(null)}><AlertDialogContent><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{confirm?.description}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>ยกเลิก</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>confirm&&run(confirm.action)}>ยืนยัน</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <footer>FFL <span>FC FRIENDS LEAGUE · MADE FOR THE GAME</span></footer></main>
}
