import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {initialState,fixtures,standings} from '../lib/league.ts';
import {scoreMessage,pushLine,verifySignature} from '../lib/line.ts';
const s=initialState();s.competitions.push({id:'c1',name:'คืนวันศุกร์',date:'2026-10-05',seasonId:'season-1',players:s.profiles.map(p=>p.id),legs:1,archived:false});s.matches.push(...fixtures(s.profiles.map(p=>p.id),1,'c1'));
const m=s.matches[0];m.hs=2;m.as=1;m.revision=1;const ev={id:crypto.randomUUID(),matchId:m.id,before:[null,null],after:[2,1],time:new Date().toISOString(),revision:1,kind:'บันทึกผล'};
const name=id=>s.profiles.find(p=>p.id===id).name;
let text=scoreMessage(s,m,ev,standings(s,'season-1'));
assert.ok(text.includes('คืนวันศุกร์'));assert.ok(text.includes(`${name(m.home)} 2–1 ${name(m.away)}`));assert.ok(!text.includes('แก้จาก'));assert.ok(text.includes(`1. ${name(m.home)} 3 แต้ม`));assert.equal(text.split('\n').filter(l=>/^\d\. /.test(l)).length,4);assert.ok(!text.includes('✍️'));
assert.ok(scoreMessage(s,m,{...ev,by:'player-2'},[]).includes(`✍️ บันทึกโดย ${name('player-2')}`));assert.ok(scoreMessage(s,m,{...ev,by:'legacy'},[]).includes('✍️ บันทึกด้วยรหัสกลาง'));
text=scoreMessage(s,m,{...ev,before:[1,1]},[]);assert.ok(text.includes('(แก้จาก 1–1)'));assert.ok(!text.includes('อันดับ'));
let req;const fake=status=>async(url,init)=>{req={url,init};return new Response('{}',{status})};
assert.equal(await pushLine({token:'t',to:'C1',text:'hi',retryKey:ev.id,fetchImpl:fake(200)}),'sent');
assert.equal(req.url,'https://api.line.me/v2/bot/message/push');assert.equal(req.init.headers.Authorization,'Bearer t');assert.equal(req.init.headers['X-Line-Retry-Key'],ev.id);assert.deepEqual(JSON.parse(req.init.body),{to:'C1',messages:[{type:'text',text:'hi'}]});
assert.equal(await pushLine({token:'t',to:'C1',text:'hi',retryKey:ev.id,fetchImpl:fake(409)}),'sent');
const quiet=console.error;console.error=()=>{};
assert.equal(await pushLine({token:'t',to:'C1',text:'hi',retryKey:ev.id,fetchImpl:fake(401)}),'failed');
assert.equal(await pushLine({token:'t',to:'C1',text:'hi',retryKey:ev.id,fetchImpl:async()=>{throw new Error('timeout')}}),'failed');
console.error=quiet;
const body='{"events":[]}',sig=createHmac('sha256','secret').update(body).digest('base64');
assert.equal(await verifySignature(body,sig,'secret'),true);assert.equal(await verifySignature(body,sig,'other'),false);assert.equal(await verifySignature(body,null,'secret'),false);
console.log('line tests passed');
