import assert from 'node:assert/strict';
import {standings} from '../lib/league.ts';
const base='http://localhost:5173';let cookie='';
const get=async()=>{const r=await fetch(base+'/api/league',{headers:{cookie}});assert.equal(r.status,200);return r.json()};
async function post(body,status=200){const r=await fetch(base+'/api/league',{method:'POST',headers:{'Content-Type':'application/json',origin:base,cookie},body:JSON.stringify(body)});const j=await r.json();assert.equal(r.status,status,JSON.stringify(j));const c=r.headers.get('set-cookie');if(c){const pair=c.split(';')[0];const key=pair.split('=')[0];cookie=cookie.split(';').map(x=>x.trim()).filter(x=>x&&!x.startsWith(key+'=')).concat(pair).join('; ');}return j}
let d=await get();assert.equal(d.state.profiles.length,4);await post({action:'season',name:'forbidden'},401);
const login=await fetch(base+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});cookie=login.headers.get('set-cookie')?.split(';')[0]||'';d=await get();assert.equal(d.setupAllowed,true);assert.equal(d.configured,false,'This test only runs against a fresh local DB');
const password=crypto.randomUUID();await post({action:'setup',password});d=await get();assert.equal(d.authenticated,true);
await post({action:'competition',version:d.version,competition:{name:'ทดสอบระบบ · ไม่ใช่ผลจริง',date:'2026-09-27',seasonId:'season-1',players:d.state.profiles.map(p=>p.id),legs:2}});d=await get();assert.equal(d.state.matches.length,12);const m=d.state.matches[0];const event=await post({action:'score',version:d.version,id:m.id,hs:3,as:1});await post({action:'score',version:d.version,id:m.id,hs:7,as:1},409);d=await get();assert.equal(standings(d.state,'season-1')[0].points,3);
await post({action:'restore',version:d.version,id:m.id,eventId:event.eventId,undo:true});d=await get();assert.equal(d.state.matches[0].hs,null);assert.equal(d.state.history.length,2);
await post({action:'score',version:d.version,id:m.id,hs:-1,as:0},400);
await post({action:'competition',version:d.version,competition:{...d.state.competitions[0],legs:1}},400);
const first=await post({action:'score',version:d.version,id:m.id,hs:2,as:2});d=await get();await post({action:'score',version:d.version,id:m.id,hs:5,as:2});d=await get();await post({action:'restore',version:d.version,id:m.id,eventId:first.eventId,undo:true},400);
const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl1sAAAAASUVORK5CYII=','base64');const upload=await fetch(base+'/api/badge',{method:'POST',headers:{origin:base,cookie,'Content-Type':'image/png'},body:bytes});assert.equal(upload.status,200);const {key}=await upload.json();const image=await fetch(base+'/api/badge?key='+key);assert.equal(image.status,200);assert.equal((await image.arrayBuffer()).byteLength,bytes.length);
await post({action:'profile',version:d.version,profile:{...d.state.profiles[0],team:'QA Club',badge:key}});d=await get();assert.equal(d.state.profiles[0].team,'QA Club');assert.equal(d.state.history.length,4);
await post({action:'profile',version:d.version,profile:{...d.state.profiles[0],team:'',badge:''}});d=await get();await post({action:'archive',version:d.version,id:d.state.competitions[0].id,archived:true});d=await get();assert.equal(standings(d.state,'season-1').length,0);await post({action:'logout'});d=await get();assert.equal(d.authenticated,false);await post({action:'login',password});d=await get();assert.equal(d.authenticated,true);await post({action:'logout'});
console.log('PASS auth, validation, persistence, 12 fixtures, scores, concurrent edits, undo, stale undo rejection, structural lock, R2 upload/read, profile edit, archive, logout/login');
