// Member-account API tests against the built Worker (run `npm run build` first). See scripts/test-server.mjs.
import assert from 'node:assert/strict';
import {initialState} from '../lib/league.ts';
import {startServer,steps,userRow,hash,sessionId,sql,OWNER} from './test-server.mjs';
// League row as it exists before accounts: one played match whose history event has no 'by'.
const old=initialState();old.competitions.push({id:'comp-old',name:'before accounts',date:'2026-09-01',seasonId:'season-1',players:['player-1','player-2'],legs:1,archived:false});old.matches.push({id:'m-old',competitionId:'comp-old',home:'player-1',away:'player-2',round:1,hs:1,as:0,revision:1});old.history.push({id:'ev-old',matchId:'m-old',before:[null,null],after:[1,0],time:'2026-09-01T12:00:00.000Z',revision:1,kind:'บันทึกผล'});
// Leftovers of the retired shared password (a settings row and a live session without user_id) must not grant anything.
const LEGACY='legacy-password-1',LEGACY_TOKEN='legacy-session-token';
const seed=[`INSERT INTO league (id,payload,version) VALUES ('main','${sql(JSON.stringify(old))}',5);`,`INSERT INTO settings (id,hash,salt) VALUES ('password','${hash(LEGACY,'legacy-salt')}','legacy-salt');`,`INSERT INTO sessions (id,expires,user_id) VALUES ('${sessionId(LEGACY_TOKEN)}',${Date.now()+43200000},NULL);`,
 userRow('u-tester','Tester','player-2','member','tester-password'),
 userRow('u-fresh','fresh','player-3','member','temp-pass-123',{mustChange:1}),
 userRow('u-off','offline','player-4','member','offline-password',{disabled:1}),
 userRow('u-many','many','player-9','member','many-password')].join('\n');
const server=await startServer({seed}),{Client,send,base}=server;
const TEMP=/^[A-HJ-NP-Za-km-np-z2-9]{4}-[A-HJ-NP-Za-km-np-z2-9]{4}-[A-HJ-NP-Za-km-np-z2-9]{4}$/;
await steps(server,async step=>{
const admin=new Client();let newProfile='',newbieTemp='',testerKeep;
await step('anonymous read-only',async()=>{const a=new Client();const d=await a.league();assert.equal(d.me,null);assert.equal(d.authenticated,false);assert.ok(!('configured' in d));await a.edit({action:'season',name:'x'},401);await a.req('/api/badge',new Uint8Array(0),{status:401,headers:{'Content-Type':'image/png'}})});
await step('shared password is retired',async()=>{const a=new Client();await a.req('/api/league',{action:'login',password:LEGACY},{status:401});await a.req('/api/league',{action:'setup',password:LEGACY},{status:401,headers:OWNER});const l=new Client();l.cookie='ffl_session='+LEGACY_TOKEN;assert.equal((await l.league()).me,null);await l.edit({action:'season',name:'x'},401)});
await step('first admin: owner only, once',async()=>{const a=new Client();assert.equal((await a.league()).hasAdmin,false);await a.auth({action:'bootstrap',username:'kevin',password:'admin-password',profileId:'player-1'},403);await admin.req('/api/auth',{action:'bootstrap',username:'kevin',password:'admin-password',profileId:'nope'},{status:400,headers:OWNER});await admin.req('/api/auth',{action:'bootstrap',username:'kevin',password:'admin-password',profileId:'player-1'},{headers:OWNER});const d=await admin.league();assert.equal(d.hasAdmin,true);assert.equal(d.me.role,'admin');assert.equal(d.me.profileId,'player-1');assert.equal(d.me.mustChangePassword,false);await new Client().req('/api/auth',{action:'bootstrap',username:'second',password:'admin-password',profileId:'player-5'},{status:403,headers:OWNER})});
await step('only admins manage accounts',async()=>{await new Client().users(401);const m=new Client();await m.auth({action:'login',username:'tester',password:'tester-password'});await m.users(403);await m.manage({action:'create',username:'sneaky',profileId:'player-1'},403)});
await step('admin creates a member with a one-time temporary password',async()=>{await admin.edit({action:'profile',profile:{name:'Newbie',team:'',badge:'',active:true}});const d=await admin.league();newProfile=d.state.profiles.find(p=>p.name==='Newbie').id;await admin.edit({action:'profile',profile:{name:'Benched',team:'',badge:'',active:false}});const benched=(await admin.league()).state.profiles.find(p=>p.name==='Benched').id;
 await admin.manage({action:'create',username:'dup',profileId:'player-2'},409);await admin.manage({action:'create',username:'ghost',profileId:'nope'},400);await admin.manage({action:'create',username:'benched',profileId:benched},400);await admin.manage({action:'create',username:'x',profileId:newProfile},400);await admin.manage({action:'create',username:'TESTER',profileId:newProfile},409);
 const r=await admin.manage({action:'create',username:'newbie',profileId:newProfile});assert.match(r.password,TEMP);newbieTemp=r.password;const u=r.users.find(x=>x.username==='newbie');assert.equal(u.mustChangePassword,true);assert.equal(u.role,'member');assert.equal(u.profileId,newProfile);assert.ok(!('hash' in u)&&!('salt' in u));
 const list=await admin.users();assert.ok(list.users.every(x=>!('hash' in x)));const n=new Client();await n.auth({action:'login',username:'newbie',password:r.password});assert.equal((await n.league()).me.mustChangePassword,true);await n.edit({action:'season',name:'x'},403)});
await step('temporary password must be replaced, other sessions end',async()=>{const n=new Client(),other=new Client();await n.auth({action:'login',username:'newbie',password:newbieTemp});await other.auth({action:'login',username:'newbie',password:newbieTemp});
 await n.auth({action:'password',current:'wrong-one',next:'brand-new-pass'},400);await n.auth({action:'password',current:newbieTemp,next:'short'},400);await n.auth({action:'password',current:newbieTemp,next:newbieTemp},400);
 await n.auth({action:'password',current:newbieTemp,next:'brand-new-pass'});const d=await n.league();assert.equal(d.me.mustChangePassword,false);assert.equal(d.authenticated,true);await n.edit({action:'profile',profile:{id:newProfile,name:'Newbie',team:'Newbie FC',badge:'',active:true}});
 assert.equal((await other.league()).me,null,'other session must be revoked');await new Client().auth({action:'login',username:'newbie',password:newbieTemp},401);
 await n.auth({action:'password',current:'brand-new-pass',next:'second-new-pass'});await new Client().auth({action:'login',username:'newbie',password:'second-new-pass'});
 await new Client().auth({action:'password',current:'x',next:'whatever-123'},401)});
await step('history records who edited, old events still restore',async()=>{const m=new Client();await m.auth({action:'login',username:'tester',password:'tester-password'});
 await m.edit({action:'restore',id:'m-old',eventId:'ev-old'});let d=await m.league();const restored=d.state.history[0];assert.equal(restored.by,'player-2');assert.equal(restored.kind,'คืนค่า');assert.equal(d.state.history.find(h=>h.id==='ev-old').by,undefined,'old event must stay untouched');assert.equal(d.state.matches.find(x=>x.id==='m-old').hs,null);
 const ev=await m.edit({action:'score',id:'m-old',hs:2,as:2});d=await m.league();assert.equal(d.state.history[0].by,'player-2');
 await admin.edit({action:'restore',id:'m-old',eventId:ev.eventId});d=await admin.league();assert.equal(d.state.history[0].by,'player-1');assert.deepEqual(d.state.history[0].after,[null,null])});
// Permission table (lib/permissions.ts): tester is a member on player-2.
await step('members edit only their own profile; setup is admin-only; every result is open',async()=>{const m=new Client();await m.auth({action:'login',username:'tester',password:'tester-password'});
 const refused=async body=>{const before=(await m.league()).version;const r=await m.edit(body,403);assert.match(r.error,/[ก-๙]/);assert.equal((await m.league()).version,before,body.action+' refused but the version changed')};
 const png=new Uint8Array(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl1sAAAAASUVORK5CYII=','base64'));const {key}=await m.req('/api/badge',png,{headers:{'Content-Type':'image/png'}});
 let d=await m.league();const mine=d.state.profiles.find(p=>p.id==='player-2'),other=d.state.profiles.find(p=>p.id==='player-3');
 await m.edit({action:'profile',profile:{...mine,name:'Dioxzyp 2',team:'Tester FC',badge:key}});d=await m.league();const saved=d.state.profiles.find(p=>p.id==='player-2');assert.deepEqual([saved.name,saved.team,saved.badge,saved.active],['Dioxzyp 2','Tester FC',key,true]);
 await refused({action:'profile',profile:{...other,team:'not mine'}});await refused({action:'profile',profile:{...other,badge:key}});await refused({action:'profile',profile:{...saved,active:false}});
 await refused({action:'profile',profile:{name:'Intruder',team:'',badge:'',active:true}});await refused({action:'profile',profile:{id:'nope',name:'Ghost',team:'',badge:'',active:true}});
 await refused({action:'season',name:'member season'});await refused({action:'season',id:'season-1',name:'renamed',current:true});
 await admin.edit({action:'competition',competition:{name:'tester not playing',date:'2026-10-05',seasonId:'season-1',players:['player-1','player-3','player-4'],legs:1}});d=await m.league();const comp=d.state.competitions.find(c=>c.name==='tester not playing');
 await refused({action:'competition',competition:{name:'member comp',date:'2026-10-05',seasonId:'season-1',players:['player-2','player-3'],legs:1}});await refused({action:'competition',competition:{...comp,name:'renamed'}});
 await refused({action:'archive',id:comp.id,archived:true});
 const match=d.state.matches.find(x=>x.competitionId===comp.id);assert.ok(![match.home,match.away].includes('player-2'));
 const first=await m.edit({action:'score',id:match.id,hs:2,as:1});const second=await m.edit({action:'score',id:match.id,hs:3,as:1});
 await m.edit({action:'restore',id:match.id,eventId:second.eventId,undo:true});await m.edit({action:'score',id:match.id,hs:null,as:null});await m.edit({action:'restore',id:match.id,eventId:second.eventId});
 d=await m.league();const after=d.state.matches.find(x=>x.id===match.id);assert.deepEqual([after.hs,after.as],[2,1]);assert.deepEqual(d.state.history.slice(0,5).map(h=>[h.kind,h.by]),[['คืนค่า','player-2'],['ล้างผล','player-2'],['คืนค่า','player-2'],['บันทึกผล','player-2'],['บันทึกผล','player-2']]);assert.equal(d.state.history[4].id,first.eventId);
 // Admins: every action, including other players' profiles and the active switch.
 await admin.edit({action:'profile',profile:{...other,team:'by admin',active:false}});await admin.edit({action:'profile',profile:{...other,active:true}});await admin.edit({action:'profile',profile:{...saved,name:'Dioxzyp',team:'',badge:''}});
 await admin.edit({action:'season',name:'admin season'});await admin.edit({action:'competition',competition:{...comp,name:'renamed by admin'}});await admin.edit({action:'archive',id:comp.id,archived:true});await admin.edit({action:'archive',id:comp.id,archived:false});
 const ev=await admin.edit({action:'score',id:match.id,hs:0,as:0});await admin.edit({action:'restore',id:match.id,eventId:ev.eventId,undo:true});
 d=await admin.league();assert.equal(d.state.profiles.find(p=>p.id==='player-3').active,true);assert.equal(d.state.competitions.find(c=>c.id===comp.id).archived,false)});
await step('generic login errors',async()=>{const a=new Client();const x=await a.auth({action:'login',username:'nobody',password:'whatever-1'},401);const y=await a.auth({action:'login',username:'tester',password:'wrong-password'},401);assert.equal(x.error,y.error)});
await step('login is case-insensitive and returns me',async()=>{const a=new Client();testerKeep=a;await a.auth({action:'login',username:'TESTER',password:'tester-password'});const d=await a.league();assert.deepEqual(d.me,{id:'u-tester',username:'Tester',role:'member',profileId:'player-2',mustChangePassword:false});assert.equal(d.authenticated,true);await a.edit({action:'profile',profile:{id:'player-2',name:'Dioxzyp',team:'',badge:'',active:true}})});
await step('temporary password blocks every write',async()=>{const a=new Client();await a.auth({action:'login',username:'fresh',password:'temp-pass-123'});const d=await a.league();assert.equal(d.me.mustChangePassword,true);assert.equal(d.authenticated,false);await a.edit({action:'season',name:'x'},403);await a.req('/api/badge',new Uint8Array(0),{status:403,headers:{'Content-Type':'image/png'}})});
await step('disabled account cannot log in',async()=>{const a=new Client();await a.auth({action:'login',username:'offline',password:'offline-password'},403);await a.auth({action:'login',username:'offline',password:'nope-nope'},401)});
await step('logout ends the session',async()=>{const a=new Client();await a.auth({action:'login',username:'tester',password:'tester-password'});const prev=a.cookie;await a.auth({action:'logout'});assert.equal(a.cookie,'');a.cookie=prev;assert.equal((await a.league()).me,null)});
await step('successful logins are not rate limited',async()=>{for(let i=0;i<8;i++)await new Client().auth({action:'login',username:'many',password:'many-password'})});
await step('per-username limit leaves other accounts alone',async()=>{const a=new Client();for(let i=0;i<5;i++)await a.auth({action:'login',username:'tester',password:'bad-'+i},401);await a.auth({action:'login',username:'tester',password:'tester-password'},429);await a.auth({action:'login',username:'many',password:'many-password'})});
await step('admin reset: new temporary password, sessions ended, lockout cleared',async()=>{await new Client().auth({action:'login',username:'tester',password:'tester-password'},429);assert.ok((await testerKeep.league()).me,'tester still signed in before reset');
 const m=new Client();await m.auth({action:'login',username:'newbie',password:'second-new-pass'});await m.manage({action:'reset',id:'u-tester'},403);await admin.manage({action:'reset',id:'missing'},404);
 const r=await admin.manage({action:'reset',id:'u-tester'});assert.match(r.password,TEMP);assert.equal(r.users.find(u=>u.id==='u-tester').mustChangePassword,true);
 assert.equal((await testerKeep.league()).me,null,'existing sessions must end');await new Client().auth({action:'login',username:'tester',password:'tester-password'},401);
 const t=new Client();await t.auth({action:'login',username:'tester',password:r.password});assert.equal((await t.league()).me.mustChangePassword,true);await t.edit({action:'season',name:'x'},403);await t.auth({action:'password',current:r.password,next:'tester-password-2'});await t.edit({action:'profile',profile:{id:'player-2',name:'Dioxzyp',team:'after reset',badge:'',active:true}})});
await step('disable ends sessions and blocks login; enable keeps the password; last admin protected',async()=>{
 await admin.manage({action:'disable',id:(await admin.league()).me.id,disabled:true},400);
 const n=new Client();await n.auth({action:'login',username:'newbie',password:'second-new-pass'});await n.manage({action:'disable',id:'u-tester',disabled:true},403);
 const r=await admin.manage({action:'disable',id:(await n.league()).me.id,disabled:true});assert.equal(r.users.find(u=>u.username==='newbie').disabled,true);
 assert.equal((await n.league()).me,null,'disabled account must lose its session');await new Client().auth({action:'login',username:'newbie',password:'second-new-pass'},403);
 await admin.manage({action:'disable',id:r.users.find(u=>u.username==='newbie').id,disabled:false});await new Client().auth({action:'login',username:'newbie',password:'second-new-pass'});
 assert.ok((await admin.league()).state.profiles.some(p=>p.id===newProfile),'profile and history stay')});
await step('role changes take effect immediately; last admin cannot be demoted',async()=>{const kevin=(await admin.league()).me.id;
 await admin.manage({action:'role',id:kevin,role:'member'},400);await admin.manage({action:'role',id:kevin,role:'owner'},400);
 const n=new Client();await n.auth({action:'login',username:'newbie',password:'second-new-pass'});await n.users(403);const newbie=(await n.league()).me.id;
 await admin.manage({action:'role',id:newbie,role:'admin'});await n.users();
 await admin.manage({action:'role',id:kevin,role:'member'});await admin.users(403);await admin.edit({action:'season',name:'demoted'},403);await admin.edit({action:'profile',profile:{...(await admin.league()).state.profiles.find(p=>p.id==='player-3'),team:'demoted'}},403);assert.equal((await admin.league()).me.role,'member');
 await n.manage({action:'role',id:kevin,role:'admin'});await admin.users();await admin.edit({action:'season',name:'admin again'});await admin.manage({action:'role',id:newbie,role:'member'});await n.users(403)});
await step('per-address limit across usernames',async()=>{const a=new Client();let blocked=false;for(let i=0;i<25&&!blocked;i++){const r=await send('/api/auth',{method:'POST',headers:{'Content-Type':'application/json',origin:base},body:JSON.stringify({action:'login',username:'spray'+i,password:'bad-password'})});blocked=r.status===429}assert.ok(blocked,'IP limit never triggered');await a.auth({action:'login',username:'many',password:'many-password'},429)});
});
